# Generated by Django 5.2.17 on 2026-09-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fee Head',
                'verbose_name_plural': 'Fee Heads',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.PositiveSmallIntegerField(help_text='Semester number, for example 1, 2, 3, etc.')),
                ('academic_year', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-academic_year', 'course', 'semester'],
                'constraints': [models.UniqueConstraint(fields=('course', 'semester', 'academic_year'), name='unique_fee_structure_per_academic_context')],
            },
        ),
        migrations.CreateModel(
            name='FeeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='fees.feehead')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='fees.feestructure')),
            ],
            options={
                'verbose_name': 'Fee Component',
                'verbose_name_plural': 'Fee Components',
                'ordering': ['fee_head__name'],
                'constraints': [models.UniqueConstraint(fields=('fee_structure', 'fee_head'), name='unique_fee_head_per_structure'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fee_component_amount_positive')],
            },
        ),
    ]
