# Generated by Django 5.2.17 on 2026-09-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='fees.invoice')),
            ],
            options={
                'ordering': ['installment_number'],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'installment_number'), name='unique_installment_number_per_invoice'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='installment_amount_positive')],
            },
        ),
    ]
